---
title: "Hands On : Class 13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get 
```{r}
library(bio3d)
file.name <- get.pdb("1hsg")
hiv <- read.pdb(file.name)
read.pdb(file = file.name)
```

## Slit into seperate protein and ligand files

We will use the `trim.pdb()` function to split our input structure 
```{r}
prot <- trim.pdb(hiv, "protein")
prot
write.pdb(prot, file="1hsg_protein.pdb")
```
```{r}
lig <- trim.pdb(hiv, "ligand")
write.pdb(lig, file = "1hsg_ligand.pdb")
```

## Docking with Vina

we run this command : ~/Downloads/autodock_vina_1_1_2_mac/bin/vina --config config.txt --log log.txt

we got a fild all.pdbqt that we need to make into a PDB format
```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

```{r}
ori <- read.pdb("1hsg_ligand.pdbqt")
rmsd(ori, res)
```

# Using NMA 
```{r}
library(bio3d)
pdb <- read.pdb("1HEL")
modes <- nma(pdb) 
plot(modes, sse=pdb)

```
```{r}
mktrj(modes, mode=7, file="nma_7.pdb")
```








